services:
  # PostgreSQL Database (Standalone)
  postgres:
    image: postgres:15-alpine
    container_name: postgres_standalone
    restart: unless-stopped
    environment:
      POSTGRES_DB: foro_academico
      POSTGRES_USER: foro_user
      POSTGRES_PASSWORD: foro_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foro_user -d foro_academico"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local
    name: postgres_data

networks:
  postgres_network:
    driver: bridge
    name: postgres_network
